name: Validar Arquivo Index

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verificar-arquivo:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar codigo do repositorio
      uses: actions/checkout@v4

    - name: Verificar se o index.html existe
      run: |
        if [ -f "index.html" ]; then
          echo "Sucesso: O arquivo index.html foi encontrado!"
        else
          echo "Erro: O arquivo index.html nao existe na raiz do projeto!"
          exit 1
        fi
